//! Linux session reuses watches for reliable batches; uncertain state triggers bounded recovery.
use super::{apply, events, Metrics, Topology};
use crate::linux_inotify::Runtime;
use crate::live::{Gate, Store};
use crate::watch::{Inventory, Limits, RawEvent, Signal};
use std::io;
use std::path::Path;
use std::time::{Duration, Instant};
pub struct Native {
    pub watch: Runtime,
    pub store: Store,
    pub gate: Gate,
    pub metrics: Metrics,
    pending: Vec<RawEvent>,
    pending_since: Option<Instant>,
    correction: bool,
    epoch: Instant,
    last_audit: Instant,
}
impl Native {
    pub fn new(root: &Path, limits: Limits) -> io::Result<Self> {
        super::validate_limits(limits)?;
        Ok(Self {
            watch: Runtime::new(root, limits)?,
            store: Store::new(),
            gate: Gate::default(),
            metrics: Metrics::default(),
            pending: vec![],
            pending_since: None,
            correction: true,
            epoch: Instant::now(),
            last_audit: Instant::now(),
        })
    }
    pub fn invalidate(&mut self, signal: Signal) {
        self.pending.clear();
        self.pending_since = None;
        self.correction = true;
        self.watch.state.signal(signal);
        self.store.observe(&self.watch.state);
    }
    pub fn restore(&mut self, inventory: Inventory) {
        self.watch.restore(inventory);
        self.pending.clear();
        self.pending_since = None;
        self.correction = true;
        self.store.observe(&self.watch.state);
    }
    fn capture(&mut self) -> io::Result<()> {
        let Some(session) = self.watch.session.as_mut() else {
            if !self.correction {
                self.invalidate(Signal::WatchLost);
            }
            return Ok(());
        };
        let captured = match session.capture(self.watch.limits.queue) {
            Ok(batch) => batch,
            Err(error) => {
                self.watch.session.take();
                self.invalidate(Signal::WatchLost);
                return Err(error);
            }
        };
        self.watch.events_observed += captured.events.len();
        if captured.kernel_overflow {
            self.invalidate(Signal::KernelOverflow);
            return Ok(());
        }
        if captured.truncated {
            self.invalidate(Signal::UserOverflow);
            return Ok(());
        }
        let mut events = vec![];
        // IN_IGNORED generated by our own rm_watch is bookkeeping, not a new change.
        for event in captured.events {
            if session.expected_ignored.contains(&event.wd) {
                if event.mask & crate::watch::IN_IGNORED != 0 {
                    session.expected_ignored.remove(&event.wd);
                }
                continue;
            }
            events.push(event);
        }
        if events.is_empty() {
            return Ok(());
        }
        if self.pending.len().saturating_add(events.len()) > self.watch.limits.queue {
            self.invalidate(Signal::UserOverflow);
            return Ok(());
        }
        if self.pending.is_empty() {
            self.pending_since = Some(Instant::now());
        }
        self.pending.extend(events);
        self.watch.state.signal(Signal::Change);
        self.store.observe(&self.watch.state);
        if self.watch.state.reasons.contains(&Signal::UserOverflow) {
            self.correction = true;
        }
        Ok(())
    }
    pub fn tick(&mut self) -> io::Result<bool> {
        self.tick_with_hooks(|| {}, || {})
    }
    pub fn tick_with_hooks(
        &mut self,
        after_apply: impl FnMut(),
        after_build: impl FnOnce(),
    ) -> io::Result<bool> {
        if let Err(error) = self.capture() {
            self.store.fail(&error);
            return Err(error);
        }
        // Low-rate insurance audit for silent missed events, not per normal change.
        if self.last_audit.elapsed() >= Duration::from_secs(30) {
            self.invalidate(Signal::Periodic);
        }
        self.store.observe(&self.watch.state);
        if !self.watch.state.dirty && !self.store.needs_update() {
            return Ok(true);
        }
        let unmatched_from = self.pending.iter().any(|event| {
            event.mask & events::FROM != 0
                && !self
                    .pending
                    .iter()
                    .any(|other| other.mask & events::TO != 0 && other.cookie == event.cookie)
        });
        if !self.correction
            && unmatched_from
            && self
                .pending_since
                .is_some_and(|t| t.elapsed() < Duration::from_millis(50))
        {
            return Ok(false);
        }
        let now = self.epoch.elapsed();
        if !self.gate.ready(now) {
            return Ok(false);
        }
        let scanned = self.watch.scanned_entries;
        let attempt = (|| {
            if self.correction {
                self.pending.clear();
                self.pending_since = None;
                if !self.watch.reconcile_with_hook(after_apply)? {
                    self.store.observe(&self.watch.state);
                    return Ok(false);
                }
                self.correction = false;
                self.last_audit = Instant::now();
            } else {
                let raw = std::mem::take(&mut self.pending);
                self.pending_since = None;
                let session = self
                    .watch
                    .session
                    .as_mut()
                    .ok_or_else(|| io::Error::other("incremental session missing"))?;
                let translated = match events::translate(
                    &self.watch.root,
                    session.paths(),
                    &session.expected_ignored,
                    &raw,
                ) {
                    Ok(t) => t,
                    Err(reason) => {
                        self.invalidate(reason);
                        return Ok(false);
                    }
                };
                if super::requires_reconcile(
                    &self.watch.root,
                    &translated.changes,
                    &mut self.metrics,
                )? {
                    self.invalidate(Signal::GenerationRace);
                    return Ok(false);
                }
                let ticket = self.watch.state.ticket();
                let next = apply(
                    &self.watch.root,
                    &self.watch.state.inventory,
                    &translated.changes,
                    self.watch.limits,
                    &mut self.metrics,
                    |edit| match edit {
                        Topology::Add(path) => session.add(&path),
                        Topology::Remove(path) => session.remove_prefix(&path),
                        Topology::Rename { from, to } => {
                            session.rename_prefix(&from, &to);
                            Ok(())
                        }
                    },
                )?;
                session.acknowledge_ignored(&translated.ignored);
                let mut hook = after_apply;
                hook();
                self.capture()?;
                if ticket != self.watch.state.generation {
                    self.correction = true;
                    self.watch.state.signal(Signal::GenerationRace);
                    self.store.observe(&self.watch.state);
                    return Ok(false);
                }
                if !self.watch.state.publish(ticket, next) {
                    self.correction = true;
                    self.store.observe(&self.watch.state);
                    return Ok(false);
                }
            }
            if !self.store.stage_delta(&self.watch.state)? {
                return Ok(false);
            }
            after_build();
            self.capture()?;
            // Reliable post-build events remain queued; the next transaction starts at the advanced inventory.
            Ok(self.store.commit(&self.watch.state))
        })();
        self.metrics.full_scans = self.watch.full_scans;
        self.metrics.scanned_entries += self.watch.scanned_entries - scanned;
        match attempt {
            Ok(ok) => {
                self.gate.completed(self.epoch.elapsed(), ok);
                Ok(ok)
            }
            Err(error) => {
                self.watch.session.take();
                self.correction = true;
                self.watch.state.signal(Signal::WatchLost);
                self.store.observe(&self.watch.state);
                self.store.fail(&error);
                self.gate.completed(self.epoch.elapsed(), false);
                Err(error)
            }
        }
    }
}
